/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlns.ui;

/**
 *
 * @author Hoanf
 */
public class ThongKeJInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ThongKeJInternalFrame
     */
    public ThongKeJInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab = new javax.swing.JTabbedPane();
        pnlLuongNhanVien = new javax.swing.JPanel();
        lblThongKeLuongNV = new javax.swing.JLabel();
        lblPhongBan = new javax.swing.JLabel();
        cboPhongBan = new javax.swing.JComboBox();
        btnXuatBaoCao = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        lblTimKiem = new javax.swing.JLabel();
        pnlTable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        pnlTongLuong = new javax.swing.JPanel();
        lblPhongBanTL = new javax.swing.JLabel();
        cboPhongBanTL = new javax.swing.JComboBox();
        btnXuatBaoCaoTL = new javax.swing.JButton();
        txtTimKiemTL = new javax.swing.JTextField();
        lblTimKiemTL = new javax.swing.JLabel();
        pnlTableTL = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTongLuong = new javax.swing.JTable();
        lblTitleTL = new javax.swing.JLabel();
        pnlNgayCong = new javax.swing.JPanel();
        lblTitleNgayCong = new javax.swing.JLabel();
        lblPhongBanNC = new javax.swing.JLabel();
        cboPhongBanNC = new javax.swing.JComboBox();
        btnXuatBaoCaoNC = new javax.swing.JButton();
        txtTimKiemNC = new javax.swing.JTextField();
        lblTimKiemNC = new javax.swing.JLabel();
        pnlNgayCongNC = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNgayCong = new javax.swing.JTable();

        lblThongKeLuongNV.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblThongKeLuongNV.setForeground(new java.awt.Color(0, 0, 255));
        lblThongKeLuongNV.setText("THỐNG KÊ LƯƠNG TỪNG NHÂN VIÊN");

        lblPhongBan.setText("Phòng ban");

        cboPhongBan.setMinimumSize(new java.awt.Dimension(260, 30));
        cboPhongBan.setPreferredSize(new java.awt.Dimension(260, 30));

        btnXuatBaoCao.setText("Xuất báo cáo");
        btnXuatBaoCao.setMaximumSize(new java.awt.Dimension(130, 40));
        btnXuatBaoCao.setMinimumSize(new java.awt.Dimension(130, 40));
        btnXuatBaoCao.setPreferredSize(new java.awt.Dimension(130, 40));

        lblTimKiem.setText("Tìm kiếm");

        pnlTable.setMinimumSize(new java.awt.Dimension(790, 420));
        pnlTable.setPreferredSize(new java.awt.Dimension(790, 420));
        pnlTable.setLayout(new java.awt.BorderLayout());

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MÃ NHÂN VIÊN", "TÊN NHÂN VIÊN", "PHÒNG BAN", "LƯƠNG"
            }
        ));
        jScrollPane2.setViewportView(tblNhanVien);

        pnlTable.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlLuongNhanVienLayout = new javax.swing.GroupLayout(pnlLuongNhanVien);
        pnlLuongNhanVien.setLayout(pnlLuongNhanVienLayout);
        pnlLuongNhanVienLayout.setHorizontalGroup(
            pnlLuongNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLuongNhanVienLayout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addComponent(pnlTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLuongNhanVienLayout.createSequentialGroup()
                .addGroup(pnlLuongNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlLuongNhanVienLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblPhongBan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTimKiem)
                        .addGap(18, 18, 18)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLuongNhanVienLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblThongKeLuongNV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXuatBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        pnlLuongNhanVienLayout.setVerticalGroup(
            pnlLuongNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLuongNhanVienLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlLuongNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXuatBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThongKeLuongNV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLuongNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhongBan)
                    .addComponent(cboPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab.addTab("LƯƠNG TỪNG NHÂN VIÊN", pnlLuongNhanVien);

        lblPhongBanTL.setText("Phòng ban");

        cboPhongBanTL.setMinimumSize(new java.awt.Dimension(260, 30));
        cboPhongBanTL.setPreferredSize(new java.awt.Dimension(260, 30));

        btnXuatBaoCaoTL.setText("Xuất báo cáo");
        btnXuatBaoCaoTL.setMaximumSize(new java.awt.Dimension(130, 40));
        btnXuatBaoCaoTL.setMinimumSize(new java.awt.Dimension(130, 40));
        btnXuatBaoCaoTL.setPreferredSize(new java.awt.Dimension(130, 40));

        lblTimKiemTL.setText("Tìm kiếm");

        pnlTableTL.setMinimumSize(new java.awt.Dimension(790, 420));
        pnlTableTL.setPreferredSize(new java.awt.Dimension(790, 420));
        pnlTableTL.setLayout(new java.awt.BorderLayout());

        tblTongLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "MÃ PHÒNG BAN", "TÊN PHÒNG BAN", "TỔNG LƯƠNG"
            }
        ));
        jScrollPane3.setViewportView(tblTongLuong);

        pnlTableTL.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        lblTitleTL.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTitleTL.setForeground(new java.awt.Color(0, 0, 255));
        lblTitleTL.setText("THỐNG KÊ TỔNG LƯƠNG THEO PHÒNG BAN");

        javax.swing.GroupLayout pnlTongLuongLayout = new javax.swing.GroupLayout(pnlTongLuong);
        pnlTongLuong.setLayout(pnlTongLuongLayout);
        pnlTongLuongLayout.setHorizontalGroup(
            pnlTongLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTongLuongLayout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addComponent(pnlTableTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTongLuongLayout.createSequentialGroup()
                .addGroup(pnlTongLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlTongLuongLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblPhongBanTL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboPhongBanTL, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTimKiemTL)
                        .addGap(18, 18, 18)
                        .addComponent(txtTimKiemTL, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTongLuongLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblTitleTL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXuatBaoCaoTL, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        pnlTongLuongLayout.setVerticalGroup(
            pnlTongLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTongLuongLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlTongLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXuatBaoCaoTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitleTL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTongLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhongBanTL)
                    .addComponent(cboPhongBanTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiemTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTimKiemTL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlTableTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab.addTab("LƯƠNG TỪNG PHÒNG BAN", pnlTongLuong);

        lblTitleNgayCong.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTitleNgayCong.setForeground(new java.awt.Color(0, 0, 255));
        lblTitleNgayCong.setText("THỐNG KÊ NGÀY CÔNG");

        lblPhongBanNC.setText("Phòng ban");

        cboPhongBanNC.setMinimumSize(new java.awt.Dimension(260, 30));
        cboPhongBanNC.setPreferredSize(new java.awt.Dimension(260, 30));

        btnXuatBaoCaoNC.setText("Xuất báo cáo");
        btnXuatBaoCaoNC.setMaximumSize(new java.awt.Dimension(130, 40));
        btnXuatBaoCaoNC.setMinimumSize(new java.awt.Dimension(130, 40));
        btnXuatBaoCaoNC.setPreferredSize(new java.awt.Dimension(130, 40));

        lblTimKiemNC.setText("Tìm kiếm");

        pnlNgayCongNC.setMinimumSize(new java.awt.Dimension(790, 420));
        pnlNgayCongNC.setPreferredSize(new java.awt.Dimension(790, 420));
        pnlNgayCongNC.setLayout(new java.awt.BorderLayout());

        tblNgayCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MÃ NHÂN VIÊN", "TÊN NHÂN VIÊN", "PHÒNG BAN", "NGÀY CÔNG"
            }
        ));
        jScrollPane1.setViewportView(tblNgayCong);

        pnlNgayCongNC.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlNgayCongLayout = new javax.swing.GroupLayout(pnlNgayCong);
        pnlNgayCong.setLayout(pnlNgayCongLayout);
        pnlNgayCongLayout.setHorizontalGroup(
            pnlNgayCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNgayCongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlNgayCongNC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNgayCongLayout.createSequentialGroup()
                .addGroup(pnlNgayCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlNgayCongLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblTitleNgayCong, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXuatBaoCaoNC, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlNgayCongLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblPhongBanNC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboPhongBanNC, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTimKiemNC)
                        .addGap(28, 28, 28)
                        .addComponent(txtTimKiemNC, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        pnlNgayCongLayout.setVerticalGroup(
            pnlNgayCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNgayCongLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlNgayCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleNgayCong)
                    .addComponent(btnXuatBaoCaoNC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(pnlNgayCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNgayCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPhongBanNC)
                        .addComponent(cboPhongBanNC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNgayCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTimKiemNC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTimKiemNC)))
                .addGap(18, 18, 18)
                .addComponent(pnlNgayCongNC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab.addTab("NGÀY CÔNG", pnlNgayCong);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tab, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXuatBaoCao;
    private javax.swing.JButton btnXuatBaoCaoNC;
    private javax.swing.JButton btnXuatBaoCaoTL;
    private javax.swing.JComboBox cboPhongBan;
    private javax.swing.JComboBox cboPhongBanNC;
    private javax.swing.JComboBox cboPhongBanTL;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblPhongBan;
    private javax.swing.JLabel lblPhongBanNC;
    private javax.swing.JLabel lblPhongBanTL;
    private javax.swing.JLabel lblThongKeLuongNV;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JLabel lblTimKiemNC;
    private javax.swing.JLabel lblTimKiemTL;
    private javax.swing.JLabel lblTitleNgayCong;
    private javax.swing.JLabel lblTitleTL;
    private javax.swing.JPanel pnlLuongNhanVien;
    private javax.swing.JPanel pnlNgayCong;
    private javax.swing.JPanel pnlNgayCongNC;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JPanel pnlTableTL;
    private javax.swing.JPanel pnlTongLuong;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTable tblNgayCong;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTable tblTongLuong;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTimKiemNC;
    private javax.swing.JTextField txtTimKiemTL;
    // End of variables declaration//GEN-END:variables
}
