package com.qlns.model;
// Generated 03/04/2020 11:10:44 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChucVu generated by hbm2java
 */
@Entity
@Table(name="ChucVu"
    ,schema="dbo"
    ,catalog="QLNS"
)
public class ChucVu  implements java.io.Serializable {


     private String maChucVu;
     private String chucVu;
     private Set<NhanVien> nhanViens = new HashSet<NhanVien>(0);
     @Override
    public String toString(){
        return this.maChucVu;
    }

    public ChucVu() {
    }

	
    public ChucVu(String maChucVu, String chucVu) {
        this.maChucVu = maChucVu;
        this.chucVu = chucVu;
    }
    public ChucVu(String maChucVu, String chucVu, Set<NhanVien> nhanViens) {
       this.maChucVu = maChucVu;
       this.chucVu = chucVu;
       this.nhanViens = nhanViens;
    }
   
     @Id 

    
    @Column(name="maChucVu", unique=true, nullable=false, length=6)
    public String getMaChucVu() {
        return this.maChucVu;
    }
    
    public void setMaChucVu(String maChucVu) {
        this.maChucVu = maChucVu;
    }

    
    @Column(name="chucVu", nullable=false)
    public String getChucVu() {
        return this.chucVu;
    }
    
    public void setChucVu(String chucVu) {
        this.chucVu = chucVu;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="chucVu")
    public Set<NhanVien> getNhanViens() {
        return this.nhanViens;
    }
    
    public void setNhanViens(Set<NhanVien> nhanViens) {
        this.nhanViens = nhanViens;
    }


}


