package com.qlns.model;
// Generated 03/04/2020 11:10:44 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NhanVien generated by hbm2java
 */
@Entity
@Table(name="NhanVien"
    ,schema="dbo"
    ,catalog="QLNS"
)
public class NhanVien  implements java.io.Serializable {

    @Override
    public String toString(){
        return this.tenNhanVien;
    }
    
     private String maNhanVien;
     private ChucVu chucVu;
     private PhongBan phongBan;
     private String matKhau;
     private String tenNhanVien;
     private double luongCoBan;
     private Date ngaySinh;
     private String diaChi;
     private String email;
     private Set<LuongThuong> luongThuongs = new HashSet<LuongThuong>(0);

    public NhanVien() {
    }

	
    public NhanVien(String maNhanVien, ChucVu chucVu, PhongBan phongBan, String matKhau, String tenNhanVien, double luongCoBan, Date ngaySinh, String diaChi, String email) {
        this.maNhanVien = maNhanVien;
        this.chucVu = chucVu;
        this.phongBan = phongBan;
        this.matKhau = matKhau;
        this.tenNhanVien = tenNhanVien;
        this.luongCoBan = luongCoBan;
        this.ngaySinh = ngaySinh;
        this.diaChi = diaChi;
        this.email = email;
    }
    public NhanVien(String maNhanVien, ChucVu chucVu, PhongBan phongBan, String matKhau, String tenNhanVien, double luongCoBan, Date ngaySinh, String diaChi, String email, Set<LuongThuong> luongThuongs) {
       this.maNhanVien = maNhanVien;
       this.chucVu = chucVu;
       this.phongBan = phongBan;
       this.matKhau = matKhau;
       this.tenNhanVien = tenNhanVien;
       this.luongCoBan = luongCoBan;
       this.ngaySinh = ngaySinh;
       this.diaChi = diaChi;
       this.email = email;
       this.luongThuongs = luongThuongs;
    }
   
     @Id 

    
    @Column(name="maNhanVien", unique=true, nullable=false, length=6)
    public String getMaNhanVien() {
        return this.maNhanVien;
    }
    
    public void setMaNhanVien(String maNhanVien) {
        this.maNhanVien = maNhanVien;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="maChucVu", nullable=false)
    public ChucVu getChucVu() {
        return this.chucVu;
    }
    
    public void setChucVu(ChucVu chucVu) {
        this.chucVu = chucVu;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="maPhongBan", nullable=false)
    public PhongBan getPhongBan() {
        return this.phongBan;
    }
    
    public void setPhongBan(PhongBan phongBan) {
        this.phongBan = phongBan;
    }

    
    @Column(name="matKhau", nullable=false, length=20)
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }

    
    @Column(name="tenNhanVien", nullable=false)
    public String getTenNhanVien() {
        return this.tenNhanVien;
    }
    
    public void setTenNhanVien(String tenNhanVien) {
        this.tenNhanVien = tenNhanVien;
    }

    
    @Column(name="luongCoBan", nullable=false, precision=53, scale=0)
    public double getLuongCoBan() {
        return this.luongCoBan;
    }
    
    public void setLuongCoBan(double luongCoBan) {
        this.luongCoBan = luongCoBan;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ngaySinh", nullable=false, length=10)
    public Date getNgaySinh() {
        return this.ngaySinh;
    }
    
    public void setNgaySinh(Date ngaySinh) {
        this.ngaySinh = ngaySinh;
    }

    
    @Column(name="diaChi", nullable=false)
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }

    
    @Column(name="email", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="nhanVien")
    public Set<LuongThuong> getLuongThuongs() {
        return this.luongThuongs;
    }
    
    public void setLuongThuongs(Set<LuongThuong> luongThuongs) {
        this.luongThuongs = luongThuongs;
    }




}


